version: '3'

services:
  nginx:
    image: chaberb/nginx-ssl
    depends_on:
      - web
      - cdn
    ports:
      - "443:443"
    volumes:
      - ./nginx-uwsgi.conf:/etc/nginx/nginx.conf
      - ./certificates/web.key:/etc/nginx/web.key
      - ./certificates/web.crt:/etc/nginx/web.crt
      - ./certificates/cdn.key:/etc/nginx/cdn.key
      - ./certificates/cdn.crt:/etc/nginx/cdn.crt

  web:
    build: web
    image: chaberb/flask-jwt
    volumes:
      - ./web:/var/www/app
    depends_on:
      - redis
    ports:
      - "5001:5000"
    environment:
      FLASK_ENV: development

  cdn:
    image: chaberb/flask-jwt
    volumes:
      - ./cdn:/var/www/app
      - ./tmp:/tmp
    ports:
      - "5002:5000"

  redis:
    image: redis
    ports:
      - "6379:6379"
